# Generated by Django 3.1.7 on 2021-03-14 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp_name', models.TextField()),
                ('cmp_shortname', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(3)])),
                ('cmp_location', models.TextField()),
                ('cmp_weburl', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5)])),
                ('email', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(15)])),
                ('password', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(8)])),
                ('status', models.CharField(max_length=1, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
            options={
                'unique_together': {('username', 'email')},
            },
        ),
    ]
